---
title: "Set Up H2O"
output: html_notebook
---

## Install

```{r}
# Remove previous versions of h2o R package
if ("package:h2o" %in% search()) detach("package:h2o", unload=TRUE)
if ("h2o" %in% rownames(installed.packages())) remove.packages("h2o")

# Next, we download R package dependencies
pkgs <- c("methods","statmod","stats","graphics",
          "RCurl","jsonlite","tools","utils")
for (pkg in pkgs) {
  if (!(pkg %in% rownames(installed.packages()))) install.packages(pkg)
}

# Download h2o package version 3.10.0.6
install.packages("h2o", type = "source", 
                 repos = "http://h2o-release.s3.amazonaws.com/h2o/rel-turing/6/R")

library(devtools)
devtools::install_github("h2oai/rsparkling", ref = "stable")

#spark_install(version = "1.6.2") # for local
```

## Test 1

```{r}
library(sparklyr)
library(rsparkling)
library(dplyr)

Sys.setenv(SPARK_HOME="/usr/lib/spark")
Sys.setenv(JAVA_HOME="/etc/alternatives/jre")

conf <- spark_config()
conf$sparklyr.shell.executor-memory <- "20g"
conf$sparklyr.shell.driver-memory <- "20g"
conf$spark.executor.cores <- 16
conf$spark.executor.memory <- "20G"
conf$spark.yarn.am.cores  <- 16
conf$spark.yarn.am.memory <- "20G"
conf$spark.dynamicAllocation.enabled <- "false"

options(rsparkling.sparklingwater.version = '1.6.7')
sc <- spark_connect(master = "yarn-client", config = config, version = '1.6.2')
airlines_tbl <- tbl(sc, "airlines")
h2oframe <- as_h2o_frame(sc, airlines_tbl)
```

## Test 2

```{r}
library(sparklyr)
library(rsparkling)
library(dplyr)
library(h2o)

mtcars_tbl <- copy_to(sc, mtcars, "mtcars", overwrite = TRUE)
partitions <- mtcars_tbl %>%
  filter(hp >= 100) %>%
  mutate(cyl8 = cyl == 8) %>%
  sdf_partition(training = 0.5, test = 0.5, seed = 1099)
training <- as_h2o_frame(sc, partitions$training)
test <- as_h2o_frame(sc, partitions$test)
glm_model <- h2o.glm(x = c("wt", "cyl"), 
                     y = "mpg", 
                     training_frame = training,
                     lambda_search = TRUE)
print(glm_model)
```

### Test 3

```{r}
trips_model_data_tbl <- tbl(sc, "trips_model_data")
trips_model_data_tbl %>% count
trips_h2o <- as_h2o_frame(sc, trips_model_data_tbl)


model_formula <- formula(tip_amount ~ fare_amount + pay_type + cab_type + passenger_count)
m1 <- ml_linear_regression(trips_train_tbl, model_formula)
summary(m1)

```
