---
title: "Browse Hive Metastore"
output: html_notebook
---

### Connect to Spark
```{r}
library(sparklyr)
library(dplyr)
library(ggplot2)
Sys.setenv(SPARK_HOME="/usr/lib/spark")
config <- spark_config()
sc <- spark_connect(master = "yarn-client", config = config, version = '2.0.0')
```

### Browse the Hive Metastore

```{r}
library(DBI)
dbGetQuery(sc, "show databases")
dbGetQuery(sc, "show tables in default")
dbGetQuery(sc, "show tables in userdb")
dbGetQuery(sc, "describe userdb.students")
```

### Create a new database, a new table, and insert data

```{r}
dbGetQuery(sc, "drop table if exists newdb.pageviews")
dbGetQuery(sc, "drop database if exists newdb")
dbGetQuery(sc, "create database newdb")
dbGetQuery(sc, "create table newdb.pageviews (userid varchar(64), link string, came_from string)")
dbGetQuery(sc, "insert into table newdb.pageviews values ('jsmith', 'mail.com', 'sports.com'), ('jdoe', 'mail.com', null)")
```

### This query does not work from R but does work from the command prompt

```{r}
dbGetQuery(sc, "CREATE TABLE students (name VARCHAR(64), age INT, gpa DECIMAL(3, 2)) CLUSTERED BY (age) INTO 2 BUCKETS STORED AS ORC")
```
```
Error: org.apache.spark.sql.catalyst.parser.ParseException: Operation not allowed: CREATE TABLE ... CLUSTERED BY(line 1, pos 0) == SQL == CREATE TABLE students (name VARCHAR(64), age INT, gpa DECIMAL(3, 2)) CLUSTERED BY (age) INTO 2 BUCKETS STORED AS ORC ^^^ at org.apache.spark.sql.catalyst.parser.ParserUtils$.operationNotAllowed(ParserUtils.scala:43) at org.apache.spark.sql.execution.SparkSqlAstBuilder$$anonfun$visitCreateTable$1.apply(SparkSqlParser.scala:913) at org.apache.spark.sql.execution.SparkSqlAstBuilder$$anonfun$visitCreateTable$1.apply(SparkSqlParser.scala:901) at org.apache.spark.sql.catalyst.parser.ParserUtils$.withOrigin(ParserUtils.scala:96) at org.apache.spark.sql.execution.SparkSqlAstBuilder.visitCreateTable(SparkSqlParser.scala:901) at org.apache.spark.sql.execution.SparkSqlAstBuilder.visitCreateTable(SparkSqlParser.scala:53) at org.apache.spark.sql.catalyst.parser.SqlBaseParser$CreateTableContext.accept(SqlBaseParser.java:474) at org.antlr.v4.runtime.tre
```