---
title: "NYC Taxi"
author: "Nathan Stephens"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(ggplot2)
library(flexdashboard)
library(shiny)
library(leaflet)
```

Detail
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

### NTA Code

Select a neighborhood tabulation area (NTA) code to describe.

```{r}
selectInput('var1','Select NTA Code',list('a'=1,'b'=2,'c'=3),1)
```

Column
-----------------------------------------------------------------------

### Pickups and dropoffs by hour

```{r}
matplot(1:24, matrix(rnorm(48),24,2), type = 'l', col = 2:3, lty = 1)
```

### Map

```{r}
leaflet() %>% addTiles() %>% setView(-73.946832999999998,40.784374999999997, 12)
```

Column
-----------------------------------------------------------------------

### Cab Type

```{r}
barplot(1:3, col = 2:5)
```

### Distance

```{r}
hist(rnorm(50), col='grey')
```

### Cost

```{r}
hist(rnorm(50), col='grey')
```

Route
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

### NTA Code

```{r}
selectInput('var3','Select pickup',list('a'=1,'b'=2,'c'=3),1)

selectInput('var4','Select dropoff',list('a'=1,'b'=2,'c'=3),1)
```

Column
-----------------------------------------------------------------------

### Travel time by hour

```{r}
matplot(1:24, matrix(rnorm(48),24,2), type = 'l', col = 2:3, lty = 1)
```

### Map

```{r}
leaflet() %>% addTiles() %>% setView(-73.946832999999998,40.784374999999997, 12)
```

Column
-----------------------------------------------------------------------

### Cab Type

```{r}
barplot(1:3, col = 2:5)
```

### Distance

```{r}
hist(rnorm(50), col='grey')
```

### Cost

```{r}
hist(rnorm(50), col='grey')
```

Pickups and Dropoffs
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

### NTA Code

```{r}
selectInput('var5','Select dropoff',list('a'=1,'b'=2,'c'=3),1)
```

Column
-----------------------------------------------------------------------

### Pickup

```{r}
leaflet() %>% addTiles() %>% setView(-73.983895000000004,40.723072000000002, 12)
```


Column
-----------------------------------------------------------------------

### Dropoff

```{r}
leaflet() %>% addTiles() %>% setView(-73.961844999999997,40.767837999999998, 12)
```

