---
title: "Intro to H2O rsparkling"
output: html_notebook
---

## Setup

```{r, message=FALSE, warning=FALSE}
library(sparklyr)
library(h2o)
library(rsparkling)
library(dplyr)
library(ggplot2)

# Connect
sc <- spark_connect("local", version = "1.6.2")
mtcars_tbl <- copy_to(sc, mtcars, "mtcars", overwrite = TRUE)
```

## H2O Context

```{r}
h2o_context(sc)
```

## Partition into test and training

```{r}
# Transform our data set, and then partition into 'training', 'test'
partitions <- mtcars_tbl %>%
  filter(hp >= 100) %>%
  mutate(cyl8 = cyl == 8) %>%
  sdf_partition(training = 0.5, test = 0.5, seed = 1099)

# Convert to H20 Frame
training <- as_h2o_frame(sc, partitions$training)
test <- as_h2o_frame(sc, partitions$test)
```

## Train a linear model

```{r}
# Fit a linear model to the training dataset
glm_model <- h2o.glm(x = c("wt", "cyl"), 
                     y = "mpg", 
                     training_frame = training,
                     lambda_search = TRUE)
# Examine model
print(glm_model)
```

## Score test data and compare to actuals

```{r}
# Compute predicted values on our test dataset
pred <- h2o.predict(glm_model, newdata = test)

# Extract the true 'mpg' values from our test dataset
actual <- partitions$test %>%
  select(mpg) %>%
  rename(actual = mpg)

# Collect the results
data <- data.frame(
  collect(as_spark_dataframe(sc, pred)),
  collect(actual)
)
```

## Plot predicted vs actuals values

```{r}
# plot predicted vs. actual values
ggplot(data, aes(x = actual, y = predict)) +
  geom_abline(lty = "dashed", col = "red") +
  geom_point() +
  theme(plot.title = element_text(hjust = 0.5)) +
  coord_fixed(ratio = 1) +
  labs(
    x = "Actual Fuel Consumption",
    y = "Predicted Fuel Consumption",
    title = "Predicted vs. Actual Fuel Consumption"
  )
```


